# Generated by Django 5.1 on 2024-10-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fintech_app', '0003_rename_balance_wallet_savings_balance_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wallet',
            field=models.ManyToManyField(to='fintech_app.wallet'),
        ),
    ]
