# Generated by Django 5.1 on 2024-10-18 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fintech_app', '0003_rename_balance_wallet_savings_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='bonus_balance',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='savings_balance',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='spending_balance',
        ),
    ]
