# Generated by Django 5.1 on 2024-10-19 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fintech_app', '0010_alter_wallet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='wallet_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fintech_app.wallettype'),
            preserve_default=False,
        ),
    ]
