# Generated by Django 5.1 on 2024-10-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fintech_app', '0011_transaction_wallet_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
    ]
