# Generated by Django 5.1 on 2024-10-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fintech_app', '0014_alter_transaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='pin',
            field=models.CharField(default='0000', max_length=20),
        ),
    ]
