# Generated by Django 5.1 on 2024-10-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fintech_app', '0015_wallet_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='pin',
            field=models.CharField(default='0000', editable=False, max_length=20),
        ),
    ]
