# Generated by Django 5.1 on 2024-10-28 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fintech_app', '0016_transaction_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='pin',
        ),
    ]
